language: java

sudo: required
dist: bionic

python:
  - "2.7"

aliases:
  - &clone-mx
    |
      export MX_PATH=${TRAVIS_BUILD_DIR}/../mx
      git clone --depth 1 https://github.com/graalvm/mx.git ${MX_PATH}
      export PATH=${PATH}:${MX_PATH}
  - &use-openjdk8-jvmci
    |
      JVMCI_VERSION="jvmci-19.2-b02"
      JDK8_UPDATE_VERSION="222"
      JDK_TAR=${TRAVIS_BUILD_DIR}/../jdk.tar.gz
      curl -sSL --retry 3 -o ${JDK_TAR} https://github.com/graalvm/openjdk8-jvmci-builder/releases/download/${JVMCI_VERSION}/openjdk-8u${JDK8_UPDATE_VERSION}-${JVMCI_VERSION}-linux-amd64.tar.gz
      tar -C ${TRAVIS_BUILD_DIR}/.. -xzf ${JDK_TAR}
      export JAVA_HOME=${TRAVIS_BUILD_DIR}/../openjdk1.8.0_${JDK8_UPDATE_VERSION}-${JVMCI_VERSION}
  - &use-graalvm
    |
      GRAAL_VM_VERSION=19.2.1
      GRAAL_VM_TARBALL=graalvm-ce-linux-amd64-${GRAAL_VM_VERSION}.tar.gz
      pushd ~/ > /dev/null
      curl -sSL --retry 3 -o ${GRAAL_VM_TARBALL} https://github.com/oracle/graal/releases/download/vm-${GRAAL_VM_VERSION}/${GRAAL_VM_TARBALL}
      tar -xzf ${GRAAL_VM_TARBALL}
      export JAVA_HOME=$(pwd)/graalvm-ce-${GRAAL_VM_VERSION}
      popd > /dev/null
  - &configure-python-for-pylint
    addons:
      apt:
        packages:
          - python-pip
          - python-virtualenv
  - &install-pylint
    |
      virtualenv ~/venv
      source ~/venv/bin/activate
      pip install astroid==1.1.0
      pip install pylint==1.1.0
  - &download-eclipse
    |
      pushd ${TRAVIS_BUILD_DIR}/.. > /dev/null
      local eclipse_tar="ci-dep-eclipse-SDK-4.5.2-linux-gtk-x86_64.tar.gz"
      ${TRAVIS_BUILD_DIR}/scripts/download-file.sh "${eclipse_tar}" 0.8.0
      tar -xzf ${eclipse_tar}
      export ECLIPSE_EXE=$(pwd)/eclipse/eclipse
      popd > /dev/null
  - &download-ecj
    |
      export JDT=${MX_PATH}/ecj.jar
      local ecj_tar="ci-dep-ecj-4.5.2.jar"
      ${TRAVIS_BUILD_DIR}/scripts/download-file.sh "${ecj_tar}" 0.8.0 "${JDT}"
  - &openjdk8-jvmci-test-setup # set up jvmci, download image, enable coverage testing
    install: *use-openjdk8-jvmci
    before_script:
      - scripts/download-test-image.sh
      - curl -sSL --retry 3 -o ~/codacy-coverage-reporter.jar "https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.3/codacy-coverage-reporter-4.0.3-assembly.jar"
      - export MX_OPTS="--jacocout coverage"
    after_success:
      - bash <(curl -s https://codecov.io/bash)
      - java -jar ~/codacy-coverage-reporter.jar report -l Java -r jacoco.xml
  - &graalvm-test-setup # set up graalvm and download image
    install: *use-graalvm
    before_script: scripts/download-test-image.sh
    script: mx --dy /compiler gate ${MX_OPTS} --strict-mode --tags ${GATE}
  - &jdk11-test-setup # set up oraclejdk11 and download image
    jdk: oraclejdk11
    before_script: scripts/download-test-image.sh

before_install: *clone-mx

script: mx gate ${MX_OPTS} --strict-mode --tags ${GATE}

jobs:
  include:
    - env: JDK="openjdk8" GATE="style,fullbuild"
      script: 
        - mx gate --strict-mode --tags ${GATE}
        - scripts/make_component.sh
      install:
        - *use-openjdk8-jvmci
        - *install-pylint
        - *download-eclipse
        - *download-ecj
      <<: *configure-python-for-pylint
    - env: JDK="openjdk8" GATE="build,test" ARCH="64bit"
      <<: *openjdk8-jvmci-test-setup
    - env: JDK="graalvm" GATE="build,test" ARCH="64bit"
      <<: *graalvm-test-setup
    - env: SUBSTRATE_VM=true
      script:
        - mx squeak-svm
        - bin/graalsqueak-svm --version:graalvm
      language: c
      addons:
        apt:
          packages:
            - libsdl2-dev
      install: *use-openjdk8-jvmci
    - env: JDK="openjdk8" GATE="build,test" ARCH="32bit"
      <<: *openjdk8-jvmci-test-setup
    - env: JDK="graalvm" GATE="build,test" ARCH="32bit"
      <<: *graalvm-test-setup
  fast_finish: true
